import {
  Atom,
  Triangle,
  Braces,
  FileType2,
  Code2,
  Palette,
  LayoutGrid,
  Wind,
  Server,
  Route,
  Webhook,
  KeyRound,
  Leaf,
  Database,
  Flame,
  Hexagon,
  Wallet,
  CreditCard,
  Globe,
  Plug,
  Bug,
  ShieldAlert,
  ScanSearch,
  Cloud,
  MonitorSmartphone,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  react: Atom,
  nextjs: Triangle,
  angular: Hexagon,
  js: Braces,
  ts: FileType2,
  html: Code2,
  css: Palette,
  bootstrap: LayoutGrid,
  tailwind: Wind,
  node: Server,
  express: Route,
  api: Webhook,
  jwt: KeyRound,
  mongodb: Leaf,
  mysql: Database,
  firebase: Flame,
  postgresql: Database,
  paypal: Wallet,
  stripe: CreditCard,
  google: Globe,
  plug: Plug,
  bug: Bug,
  error: ShieldAlert,
  debug: ScanSearch,
  hosting: Cloud,
};

export default function TechIcon({ icon, size = 18 }: { icon: string; size?: number }) {
  const Icon = ICON_MAP[icon] ?? MonitorSmartphone;
  return <Icon size={size} strokeWidth={2} />;
}
